[build]
  command = "npm run build"
  publish = "dist"

[build.processing]
  skip_processing = true

[context.production.environment]
  NETLIFY_DRAWER = "false"
  NETLIFY_ENABLE_FEEDBACK = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
